### ISSUE TITLE
Installation fails for OSX because of GitHub behavior

### ISSUE THREAD

**Issue by bradbaris** [imagemin/mozjpeg-bin#21]
Installation fails at pre-build on MacOS because it looks for a self-ref to the repo at: https://raw.githubusercontent.com/imagemin/mozjpeg-bin/v4.1.2/vendor/macos/cjpeg which technically exists, but doesn't work.

The binary is still at https://raw.githubusercontent.com/imagemin/mozjpeg-bin/v4.1.2/vendor/osx/cjpeg which retrieves the file and redirects to .../macos/cjpeg

**Comment by Nettsentrisk** [comment]
This also fails when Github is having issues, as is the case right now (degraded almost across the board).

Getting this when running an npm install now for this library and also optipng-bin: 

> ΓÇ╝ Response code 502 (Gateway Error)
>     ΓÇ╝ mozjpeg pre-build test failed
>     i compiling from source
>     ├ù HTTPError: Response code 502 (Bad Gateway)
>       at EventEmitter.<anonymous> (D:\a\1\s\src\WebSite\node_modules\got\index.js:250:24)
>       at EventEmitter.emit (events.js:315:20)
>       at Immediate.<anonymous> (D:\a\1\s\src\WebSite\node_modules\got\index.js:99:8)
>       at processImmediate (internal/timers.js:461:21)
