### ISSUE TITLE
Self signed certificate in chain problems 

### ISSUE THREAD

**Issue by jamasu** [imagemin/mozjpeg-bin#24]
Hi,
i am getting this error while trying to install mozjpeg:
src\Frontend\node_modules\mozjpeg
> node lib/install.js

  ‼ self signed certificate in certificate chain
  ‼ mozjpeg pre-build test failed
  i compiling from source
  x RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (c:\Users\pa_suja\Documents\norgesportalen\EpiS
erver\src\Frontend\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN norgesportalen@1.0.0 No repository field.

Any suggestions?

**Comment by sevaru** [comment]
It's probably mean that you are under some proxy.
You could
1) properly set you proxy options
or 
2) NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by ted-regino** [comment]
properly set you proxy options .  --->  This did not work for me.
or
NODE_TLS_REJECT_UNAUTHORIZED=0 . ---> This worked for me.

**Comment by richie50** [comment]
@ted-regino where do you set that in a docker build and installing the dependencies over npm
